#!/bin/bash

set -euo pipefail

cd ~/Programming/Vim/vim

make distclean
./configure --prefix ~/Programming/Vim/built --with-features=huge --enable-perlinterp --enable-pythoninterp --enable-rubyinterp --enable-multibyte --enable-fontset
make
make install
