#!/bin/bash

set -euo pipefail

readonly COMMAND="$(readlink -f "${0}")"
readonly DIR_NAME="$(dirname "${COMMAND}")"
readonly BUILD_FOLDER="${DIR_NAME}/built"
readonly VIM_PROJECT="https://github.com/vim/vim"

cd "${DIR_NAME}"

if [ ${#@} -ge 1 ] && [ "${1}" = "--no-sudo" ]
then
    echo "Not installing dependencies"
else
    echo "Installing dependencies"
    sudo apt-get install git
    sudo apt-get build-dep vim
fi

echo "Downloading source code"
[ ! -e vim ] && git clone "${VIM_PROJECT}" vim
(
    cd vim
    git pull --rebase
)

echo "Building vim to ${BUILD_FOLDER}"
(
    cd vim

    make distclean
    ./configure                    \
        --prefix "${BUILD_FOLDER}" \
        --with-features=huge       \
        --enable-cscope            \
        --enable-fail-if-missing   \
        --enable-fontset           \
        --enable-gnome-check       \
        --enable-gtk2-check        \
        --enable-gui=auto          \
        --enable-luainterp         \
        --enable-multibyte         \
        --enable-mzschemeinterp    \
        --enable-perlinterp        \
        --disable-pythoninterp     \
        --enable-python3interp     \
        --enable-rubyinterp        \
        --enable-tclinterp         \
        --enable-terminal          \
        --enable-xim               \
        --with-x
    make
    make install
)
